### ISSUE TITLE
[question] Is it possible to also include systemmonitor?

### ISSUE THREAD

**Issue by clst** [zvova7890/ksysguard6#1]
Hi thanks for porting this. I love it!

And all my settings and pages are back.

It was included in Plasma-Workspace5

I just grabbed the binary `systemmonitor` from plasma-workspace-5.27.9.1 and manually copied those libs:
```
libKSysGuardFormatter.so.1
libkworkspace5.so.5
libprocesscore.so.9
libprocessui.so.9
```
And it seems to work fine alongside this ksysguard version. It's not registered in DBUS but it runs. And I can restore the old CTRL+ESC task manager.

I guess it would break in the future so maybe you could integrate it into ksysguard6.
I would try it myself but the kde frameworks code confuses me to no end, whenever I try hacking on it.

**Comment by zvova7890** [comment]
Thanks for your feedback! I love it too :+1: 

As about systemmonitor, it was a part of the plasma-desktop package. However, transferring this is not as difficult as it might seem.
Please try [systemmonitor](https://github.com/zvova7890/ksysguard6/tree/systemmonitor) branch

**Comment by clst** [comment]
That built and ran like charm. Thanks again.
