### ISSUE TITLE
regexpSensorName gets enclosed by \A(?: and )\z

### ISSUE THREAD

**Issue by maxmitti** [zvova7890/ksysguard6#8]
Every time KSysGuard is opened, regular expressions of sensors get enclosed by an additional `\A(?:` and `)\z`.
This appears to be caused by `QRegularExpression::anchoredPattern` and `QRegularExpression::pattern`.

It can be observed in Tab files (.sgrd) or when opening the “Properties” of the “CPU History” graph from the default “System Load” tab via the context menu and then navigating to the “Sensors” tab.

![image](https://github.com/user-attachments/assets/82613ca0-f061-48df-994c-d5977a79f119)

**Comment by zvova7890** [comment]
We probably need an upgrade step to de-anchor existing saved patterns... But I don't see a good way for that.
I also noticed a bug where, after using KSysGuard for a while, it stops displaying sensor data. Probably the RegExp becomes too large and stops working.

@maxmitti Can you also test #9? Just to ensure nothing is broken

**Comment by maxmitti** [comment]
Yes, it works :)
Thanks!
